# src/grimoire/bind/semantiscan.py
"""
Semantiscan binding target.

Exports spells into two formats consumable by semantiscan:

1. **TOML (PromptManager)**: Separate ``system`` and ``user`` prompts
   with defaults, loaded by semantiscan's ``PromptManager``.

2. **Legacy ``.tmpl``**: Single-string templates using ``{context}``
   and ``{question}`` placeholders, compatible with semantiscan's
   legacy template renderer.

Variable mapping:
    Grimoire ``{{ var }}`` → semantiscan ``{var}``
    Grimoire built-ins → semantiscan built-ins (e.g. grimoire.now.date → current_date)

References:
    Spec §10.1, draft spec §9.1
"""

from __future__ import annotations

import logging
import re
from typing import Any

from grimoire.bind.base import Binder, BindFormat, BindResult, BindTarget, BoundFile
from grimoire.models import MessageRole, Spell
from grimoire.store.repo import GrimoireRepo

logger = logging.getLogger(__name__)

# Grimoire {{var}} → semantiscan {var}
_GRIMOIRE_VAR_RE = re.compile(r"\{\{\s*([a-zA-Z_][a-zA-Z0-9_.]*)\s*\}\}")
_GRIMOIRE_VAR_DEFAULT_RE = re.compile(
    r"\{\{\s*([a-zA-Z_][a-zA-Z0-9_.]*)\s*\|\s*default\(\s*[\"']?([^\"')]*)[\"']?\s*\)\s*\}\}"
)
_GRIMOIRE_INCLUDE_RE = re.compile(r"\{\{\s*include\(\s*[\"'][^\"']+[\"']\s*\)\s*\}\}")

# Built-in variable name mapping: grimoire → semantiscan
_BUILTIN_MAP: dict[str, str] = {
    "grimoire.now.date": "current_date",
    "grimoire.now.iso": "current_datetime",
    "grimoire.now.time": "current_time",
    "grimoire.host.hostname": "hostname",
    "grimoire.host.username": "username",
    "grimoire.git.repo_name": "repo_name",
    "grimoire.git.ref": "git_ref",
}


def _convert_vars_to_semantiscan(text: str) -> str:
    """
    Convert grimoire template syntax to semantiscan syntax.

    - ``{{ var }}`` → ``{var}``
    - ``{{ var|default("x") }}`` → ``{var}`` (defaults handled in TOML metadata)
    - ``{{ include("...") }}`` → removed (includes must be pre-resolved)
    - Built-in remapping (grimoire.now.date → current_date)
    """
    # Remove include directives (should already be resolved before binding)
    result = _GRIMOIRE_INCLUDE_RE.sub("", text)

    # Convert var|default → {var}
    def _replace_default(m: re.Match) -> str:
        name = m.group(1)
        return "{" + _BUILTIN_MAP.get(name, name) + "}"

    result = _GRIMOIRE_VAR_DEFAULT_RE.sub(_replace_default, result)

    # Convert plain vars → {var}
    def _replace_var(m: re.Match) -> str:
        name = m.group(1)
        return "{" + _BUILTIN_MAP.get(name, name) + "}"

    result = _GRIMOIRE_VAR_RE.sub(_replace_var, result)

    return result.strip()


def _spell_to_toml(spell: Spell) -> str:
    """
    Convert a spell to semantiscan PromptManager TOML format.

    Produces a TOML file with sections:
        [metadata]
        [prompts]
        [defaults]
    """
    lines: list[str] = []

    # Header comment
    lines.append("# Auto-generated by grimoire bind semantiscan --format toml")
    lines.append(f"# Source spell: {spell.id} v{spell.version}")
    lines.append("# DO NOT EDIT — regenerate with: grimoire bind semantiscan")
    lines.append("")

    # [metadata]
    lines.append("[metadata]")
    lines.append(f'name = "{spell.id}"')
    lines.append(f'description = "{spell.name}"')
    lines.append(f'version = "{spell.version}"')
    if spell.tags:
        tags_str = ", ".join(f'"{t}"' for t in spell.tags)
        lines.append(f"tags = [{tags_str}]")
    lines.append("")

    # Extract blocks
    system_parts: list[str] = []
    user_parts: list[str] = []
    for block in spell.raw_blocks:
        converted = _convert_vars_to_semantiscan(block.content)
        if block.role in (MessageRole.SYSTEM, MessageRole.DEVELOPER):
            system_parts.append(converted)
        elif block.role == MessageRole.USER:
            user_parts.append(converted)

    # [prompts]
    lines.append("[prompts]")
    system_text = "\n\n".join(system_parts) if system_parts else ""
    user_text = "\n\n".join(user_parts) if user_parts else ""

    # Use TOML multi-line strings for long prompts
    lines.append('system = """')
    lines.append(system_text)
    lines.append('"""')
    lines.append("")
    lines.append('user = """')
    lines.append(user_text)
    lines.append('"""')
    lines.append("")

    # [defaults]
    defaults: dict[str, Any] = {}
    for name, spec in spell.variables.items():
        if spec.default is not None:
            defaults[name] = spec.default
    if defaults:
        lines.append("[defaults]")
        for k, v in defaults.items():
            if isinstance(v, str):
                # Escape for TOML
                escaped = v.replace("\\", "\\\\").replace('"', '\\"')
                lines.append(f'{k} = "{escaped}"')
            elif isinstance(v, bool):
                lines.append(f"{k} = {str(v).lower()}")
            elif isinstance(v, (int, float)):
                lines.append(f"{k} = {v}")
            else:
                lines.append(f'{k} = "{v}"')
        lines.append("")

    return "\n".join(lines)


def _spell_to_legacy_tmpl(spell: Spell) -> str:
    """
    Convert a spell to semantiscan legacy ``.tmpl`` format.

    Produces a single-string template with ``{context}`` and ``{question}``
    placeholders. If the spell doesn't use these, they're appended.
    """
    # Combine all blocks into a single template string
    parts: list[str] = []
    for block in spell.raw_blocks:
        converted = _convert_vars_to_semantiscan(block.content)
        if block.role in (MessageRole.SYSTEM, MessageRole.DEVELOPER):
            parts.append(converted)
        elif block.role == MessageRole.USER:
            parts.append(converted)

    template = "\n\n".join(parts)

    # Ensure {context} and {question} are present (semantiscan requirement)
    has_context = "{context}" in template
    has_question = "{question}" in template

    if not has_context or not has_question:
        template += "\n"
        if not has_context:
            template += "\n## Context\n{context}\n"
        if not has_question:
            template += "\n## Question\n{question}\n"

    return template


class SemantiscanBinder(Binder):
    """
    Bind grimoire artifacts to semantiscan-compatible formats.

    Supports:
        - ``toml``: PromptManager TOML files
        - ``legacy_tmpl``: Single-string ``.tmpl`` files
    """

    @property
    def target(self) -> BindTarget:
        return BindTarget.SEMANTISCAN

    @property
    def default_format(self) -> BindFormat:
        return BindFormat.TOML

    def bind(
        self,
        repo: GrimoireRepo,
        *,
        fmt: BindFormat | None = None,
        spell_ids: list[str] | None = None,
        rune_ids: list[str] | None = None,
        tags: list[str] | None = None,
    ) -> BindResult:
        """Export spells to semantiscan format."""
        fmt = fmt or self.default_format
        result = BindResult(
            target=self.target,
            format=fmt,
            metadata={"grimoire": repo.manifest.name, "version": repo.manifest.version},
        )

        # Select spells
        if spell_ids:
            spells = []
            for sid in spell_ids:
                try:
                    spells.append(repo.get_spell(sid))
                except Exception:
                    result.warnings.append(f"Spell '{sid}' not found, skipped")
        else:
            spells = repo.list_spells(tags=tags)

        if not spells:
            result.warnings.append("No spells matched the filter criteria")
            return result

        for spell in spells:
            safe_id = spell.id.replace("/", "_")
            try:
                if fmt == BindFormat.TOML:
                    content = _spell_to_toml(spell)
                    result.files.append(
                        BoundFile(
                            relative_path=f"{safe_id}.toml",
                            content=content,
                            description=f"PromptManager TOML for {spell.id}",
                        )
                    )
                elif fmt == BindFormat.LEGACY_TMPL:
                    content = _spell_to_legacy_tmpl(spell)
                    result.files.append(
                        BoundFile(
                            relative_path=f"{safe_id}.tmpl",
                            content=content,
                            description=f"Legacy template for {spell.id}",
                        )
                    )
                else:
                    result.warnings.append(f"Unsupported format '{fmt}' for semantiscan target")
                    return result
            except Exception as e:
                result.warnings.append(f"Failed to bind spell '{spell.id}': {e}")
                logger.error("Bind error for %s: %s", spell.id, e, exc_info=True)

        result.metadata["spell_count"] = len(result.files)
        return result
